FROM node:14.18.1-alpine3.14

RUN apk add bash
RUN apk add git

WORKDIR /Mouthwash
COPY . /Mouthwash
RUN cd plugins && yarn

EXPOSE 20000-30000/udp

RUN yarn
RUN yarn build-all

CMD [ "yarn", "start:node" ]