export enum SubmergedSystemType {
    Nil = 0,
    Research = 128,
    Observatory,
    UpperCentral,
    UpperLobby,
    Filtration,
    Ballast,
    LowerCentral,
    LowerLobby,
    ElevatorHallwayLeft,
    ElevatorHallwayRight,
    ElevatorLobbyLeft,
    ElevatorLobbyRight,
    ElevatorService,
    Floor,
    SecuritySabotage,
    SpawnIn,
    BoxCat
}